In [2]:
import numpy as np
import pandas as pd

In [3]:
x = [1,2,3,5,1,2]
nx = np.array(x)

In [4]:
print(nx)

[1 2 3 5 1 2]


In [5]:
print(nx.shape)

(6,)


In [6]:
ny = np.array([[1,2,3],[4,5,6]])
print(ny.shape)

(2, 3)


In [7]:
ny

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
one = np.arange(1,100,.2)
one

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8,
       12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. ,
       14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2,
       16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4,
       18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2, 20.4, 20.6,
       20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4, 22.6, 22.8,
       23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6, 24.8, 25. ,
       25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8, 27. , 27.2,
       27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. , 29.2, 29.4,
       29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31

In [9]:
print(one.size)

495


In [10]:
two = np.linspace(0,100,200)
two

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [11]:
three = np.random.rand(100)
three

array([0.81423422, 0.68786842, 0.4218825 , 0.43592637, 0.25169729,
       0.17045484, 0.48341041, 0.02446139, 0.55235618, 0.48762788,
       0.85056741, 0.29996045, 0.47208677, 0.50610583, 0.85875568,
       0.00400345, 0.82971901, 0.16605676, 0.87460997, 0.17320753,
       0.58660946, 0.94229159, 0.04453952, 0.11146712, 0.36539879,
       0.86194911, 0.53493111, 0.37853829, 0.94541736, 0.8718902 ,
       0.1848499 , 0.47667689, 0.54844993, 0.62757941, 0.07542122,
       0.50484853, 0.69277767, 0.07500572, 0.8927973 , 0.79978849,
       0.07315432, 0.15104716, 0.44634989, 0.65932251, 0.06280282,
       0.96743249, 0.03940588, 0.50664478, 0.53759837, 0.46978814,
       0.55900937, 0.40270474, 0.82045787, 0.99228962, 0.04183543,
       0.22278611, 0.07288559, 0.33485866, 0.02072182, 0.04290664,
       0.59957141, 0.64532032, 0.87315185, 0.88270918, 0.63655717,
       0.63592716, 0.10609281, 0.85984131, 0.80521598, 0.64048401,
       0.34030953, 0.54069507, 0.99387506, 0.17351861, 0.86221

In [12]:
n4 = np.random.randint(1,10,100)
n4

array([4, 4, 2, 7, 3, 3, 3, 7, 7, 7, 4, 5, 3, 5, 3, 5, 2, 5, 1, 7, 4, 2,
       2, 2, 7, 3, 7, 4, 7, 7, 6, 9, 6, 4, 9, 3, 9, 1, 7, 3, 3, 2, 4, 8,
       1, 7, 4, 2, 2, 5, 4, 7, 1, 9, 5, 6, 5, 6, 7, 1, 7, 1, 2, 6, 1, 3,
       6, 8, 2, 3, 5, 3, 3, 2, 4, 4, 6, 4, 1, 8, 5, 1, 1, 8, 3, 7, 8, 4,
       1, 3, 8, 1, 5, 7, 7, 2, 1, 2, 8, 7])

In [13]:
n4.reshape((10,10))

array([[4, 4, 2, 7, 3, 3, 3, 7, 7, 7],
       [4, 5, 3, 5, 3, 5, 2, 5, 1, 7],
       [4, 2, 2, 2, 7, 3, 7, 4, 7, 7],
       [6, 9, 6, 4, 9, 3, 9, 1, 7, 3],
       [3, 2, 4, 8, 1, 7, 4, 2, 2, 5],
       [4, 7, 1, 9, 5, 6, 5, 6, 7, 1],
       [7, 1, 2, 6, 1, 3, 6, 8, 2, 3],
       [5, 3, 3, 2, 4, 4, 6, 4, 1, 8],
       [5, 1, 1, 8, 3, 7, 8, 4, 1, 3],
       [8, 1, 5, 7, 7, 2, 1, 2, 8, 7]])

In [14]:
n5 = n4.reshape((10,2,5))

In [15]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))

In [16]:
n1 + n2

array([[10,  4, 10, 10, 12],
       [14, 12, 12, 13,  9],
       [11, 14, 13, 11, 17],
       [13,  5, 11,  2,  5],
       [ 4,  9,  7, 13, 15]])

In [17]:
n1 - n2

array([[-2, -2, -2, -2, -6],
       [ 0, -2, -2,  1,  5],
       [-1, -4, -5, -7,  1],
       [ 3, -3, -7,  0, -1],
       [ 2,  7, -1,  3, -1]])

In [18]:
n1**4

array([[ 256,    1,  256,  256,   81],
       [2401,  625,  625, 2401, 2401],
       [ 625,  625,  256,   16, 6561],
       [4096,    1,   16,    1,   16],
       [  81, 4096,   81, 4096, 2401]], dtype=int32)

In [19]:
n1.dot(n2)

array([[ 78,  74, 115,  85, 106],
       [149, 136, 213, 159, 190],
       [108, 103, 155, 143, 165],
       [ 74,  55,  90,  83, 109],
       [139, 131, 201, 136, 147]])

In [20]:
n1 * n2

array([[24,  3, 24, 24, 27],
       [49, 35, 35, 42, 14],
       [30, 45, 36, 18, 72],
       [40,  4, 18,  1,  6],
       [ 3,  8, 12, 40, 56]])

In [21]:
n6 = np.random.randint(1,10,10)
print(n6)

[1 2 1 2 5 3 3 4 5 7]


In [22]:
z = np.array([[5,6,7,8],[1,3,5,5],[6,1,2,3]])
z

array([[5, 6, 7, 8],
       [1, 3, 5, 5],
       [6, 1, 2, 3]])

In [23]:
print(z[:2,1:3])

[[6 7]
 [3 5]]


In [24]:
n5.sum(axis=0)

array([[50, 35, 29, 58, 43],
       [43, 51, 43, 43, 51]])

In [25]:
n5.sum()

446

In [26]:
n5.sum(axis=1)

array([[ 7,  7,  9, 14, 10],
       [ 9,  7,  8,  6, 10],
       [ 7,  9,  6,  9, 14],
       [ 9, 18,  7, 11, 12],
       [10,  6,  6, 10,  6],
       [10, 12,  7, 16,  6],
       [10,  7, 10,  8,  4],
       [ 9,  9,  7,  3, 12],
       [12,  9,  5,  9,  6],
       [10,  2,  7, 15, 14]])

In [27]:
n6.max()

7

In [28]:
n6.argmax()

9

In [33]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (3,2))
c = np.random.randint(1,100, (2,3))

In [34]:
print(a)
print(b)
print(c)

[[66 11]
 [45 71]
 [96  7]]
[[39 55]
 [61 37]
 [39  8]]
[[13 62 65]
 [52 66 42]]


In [35]:
np.hstack((a,b))

array([[66, 11, 39, 55],
       [45, 71, 61, 37],
       [96,  7, 39,  8]])

In [36]:
np.vstack((a,b))

array([[66, 11],
       [45, 71],
       [96,  7],
       [39, 55],
       [61, 37],
       [39,  8]])

In [38]:
m = np.array([1,5,2,3,6,4,7,8,5,2,6,7,4,5,5,5,2,6,3,2,2])

In [39]:
m > 5

array([False, False, False, False,  True, False,  True,  True, False,
       False,  True,  True, False, False, False, False, False,  True,
       False, False, False])

In [40]:
m[m>5]

array([6, 7, 8, 6, 7, 6])

In [42]:
m[m != 5]

array([1, 2, 3, 6, 4, 7, 8, 2, 6, 7, 4, 2, 6, 3, 2, 2])

In [43]:
m[(m>2) & (m<6)]

array([5, 3, 4, 5, 4, 5, 5, 5, 3])